### ISSUE TITLE
DecodeError when passing Django task to Celery

### ISSUE THREAD

**Issue by derrend** [docker-library/celery#6]
I'm passing a task from my Django app to a Celery container (through [rabbit-mq](https://hub.docker.com/_/rabbitmq/)) but I keep getting the error below.
I've check that the `LANG` var is set to UTF8 (actually C.UTF8 in this case) but I haven’t found any other solutions when searching online which is why I'm posting here.

If anyone can see what the problem is I'd be most grateful.

```
[2015-09-17 23:13:33,486: CRITICAL/MainProcess] Can't decode message body: DecodeError(UnicodeDecodeError('ascii', b'\xe7\xc07\xf1\xfff\x14\x8ec\x1c\xc5\xf9\x86\xed\x86\x9a<\xe3M\xa0]x\x80\xd8;\xd5B&+8\xeab', 0, 1, 'ordinal not in range(128)'),) [type:'application/x-python-serialize' encoding:'binary' headers:{}]

body: b'\x80\x02}q\x01(U\x07expiresq\x02NU\x03utcq\x03\x88U\x04argsq\x04cpycoin.key.BIP32Node\nBIP32Node\nq\x05)\x81q\x06}q\x07(U\x06_depthq\x08K\x00U\x14_prefer_uncompressedq\t\x89U\x15_hash160_uncompressedq\nNU\x10_secret_exponentq\x0bNU\r_subkey_cacheq\x0c}U\x08_netcodeq\rU\x03BTCq\x0eU\x13_hash160_compressedq\x0fNU\x0b_chain_codeq\x10U \xe7\xc07\xf1\xfff\x14\x8ec\x1c\xc5\xf9\x86\xed\x86\x9a<\xe3M\xa0]x\x80\xd8;\xd5B&+8\xeabU\x0c_public_pairq\x11\x8a... (928b)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/kombu/messaging.py", line 590, in _receive_callback
    decoded = None if on_m else message.decode()
  File "/usr/local/lib/python3.4/site-packages/kombu/message.py", line 142, in decode
    self.content_encoding, accept=self.accept)
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 59, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.4/site-packages/kombu/five.py", line 132, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 55, in _reraise_errors
    yield
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 184, in loads
    return decode(data)
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 345, in unpickle
    return pickle_loads(str_to_bytes(s))
  File "/usr/local/lib/python3.4/site-packages/kombu/serialization.py", line 64, in pickle_loads
    return load(BytesIO(s))
kombu.exceptions.DecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)
```

Thanks in advance :)

**Comment by derrend** [comment]
UPDATE:
Turns out the object I'm serialising has a field named '_chain_code' which is causing the problem, here is an example of one - '\xe7\xc07\xf1\xfff\x14\x8ec\x1c\xc5\xf9\x86\xed\x86\x9a<\xe3M\xa0]x\x80\xd8;\xd5B&+8\xeab'. How can I make celery ignore this or prevent it from trying to serialise it?

Thanks

**Comment by derrend** [comment]
The answer was to pass the id of the database object I wanted to use to my task and then have the task retrieve the object from the database when needed. The fact that I was passing an object into my task was the problem.

**Comment by prkamath** [comment]
You have no idea my friend, how much this has helped me !!
